general {
  lock_cmd = /home/dhaval/forge/hypr/lock.sh
  before_sleep_cmd = /home/dhaval/forge/hypr/lock.sh
  after_sleep_cmd = notify-send "Woke up"
  ignore_dbus_inhibit = false
  ignore_systemd_inhibit = false
}

listener {
  timeout = 600
  on-timeout = /home/dhaval/forge/hypr/lock.sh
}

listener {
  timeout = 900
  on-timeout = systemctl suspend
}
